apiVersion: v1
kind: Service
metadata:
  name: orders-mariadb
  labels:
    app: "orders-mariadb"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3307
    targetPort: mysql
  selector:
    app: "orders-mariadb"
